//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public int ObjectId { get; set; }
        public System.DateTime DateStart { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    
        public virtual Object Object { get; set; }
    }

    
}
