//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForPractice
{
    using ForPractice.Repository;
    using NUnit.Framework;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.Event = new HashSet<Object>();
            this.PopulationObject = new HashSet<PopulationObject>();
        }
    
        public int ObjectId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Adress { get; set; }
        public int CountSeats { get; set; }
        public bool Opened_Closed { get; set; }
        public System.DateTime DateOpen { get; set; }
        public int OwnerId { get; set; }

        [NotMapped]
        public Owner owners => new OwnerRepository().GetById(OwnerId);



        public  ICollection<Object> Event { get; set; }
        public  Owner Owner { get; set; }
        public  ICollection<PopulationObject> PopulationObject { get; set; }

        
        

        public  string opened => Opened_Closed == true ? "Да" : "Нет";    
        public  string FioOwner => owners.FIO;
    }
}
