//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopulationObject
    {
        public int PopulationObjectId { get; set; }
        public int ObjectId { get; set; }
        public int CountVisited { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Object Object { get; set; }
    }
}
